engine = inform7
title = Disenchantment12
author = An Inform 7 Tutorial
description = An Inform 7 tutorial game.
binary = disenchantment12.ulx
source = story.ni
walkthrough = walkthrough.txt
tags = demo
sourceLabel = disenchantment12.ni
hub = yes
